apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  selector:
    app.kubernetes.io/name: webhook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks-deployment
  labels:
    app: webhooks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webhooks
  template:
    metadata:
      labels:
        app: webhooks
    spec:
      containers:
      - name: webhooks
        image: spiridon26/webhooks:latest
        ports:
        - containerPort: 80